steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DB=$$DATABASE_URL .
    secretEnv: [ 'DATABASE_URL' ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/dark-mark-452418-d3/store-image-registry/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/861445058623/secrets/orders_ms_db_url/versions/1
      env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY